CREATE TABLE IF NOT EXISTS "Logins" (
    "LoginID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EmployeeID" integer UNIQUE NOT NULL,
    "Username" character varying(50) UNIQUE NOT NULL,
    "Password" character varying(255) NOT NULL,
    "LastLogin" timestamp with time zone NULL,
    "FailedAttempts" integer NOT NULL DEFAULT 0,
    "IsLocked" boolean NOT NULL DEFAULT FALSE,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "FK_Logins_Employees" FOREIGN KEY ("EmployeeID")
        REFERENCES "Employees"("EmployeeID") ON DELETE CASCADE
);