CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "FaceData" (
    "FaceDataID" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeID" integer NOT NULL,
    "OriginalImage" text NOT NULL,
    CONSTRAINT "PK_FaceData" PRIMARY KEY ("FaceDataID")
);

CREATE TABLE "Attendance" (
    "AttendanceID" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeID" integer NOT NULL,
    "AttendanceDate" date NOT NULL,
    "TimeIn" time,
    "TimeOut" time,
    "Status" character varying(20) NOT NULL,
    "LunchStartTime" time,
    "LunchEndTime" time,
    "CreatedAt" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_Attendance" PRIMARY KEY ("AttendanceID")
);

CREATE TABLE "Departments" (
    "DepartmentID" integer GENERATED BY DEFAULT AS IDENTITY,
    "DepartmentName" character varying(100) NOT NULL,
    "Description" character varying(500) NOT NULL,
    "Performance" numeric(18,2) NOT NULL,
    "DateCreated" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "Budget" numeric(18,2) NOT NULL,
    "Status" character varying(50) NOT NULL DEFAULT 'Active',
    "ManagerID" integer,
    CONSTRAINT "PK_Departments" PRIMARY KEY ("DepartmentID")
);

CREATE TABLE "Employees" (
    "EmployeeID" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "Email" character varying(255),
    "PhoneNumber" character varying(20),
    "Address" character varying(500),
    "DateOfBirth" date NOT NULL,
    "Gender" character varying(10) NOT NULL,
    "DepartmentID" integer NOT NULL,
    "Position" character varying(100) NOT NULL,
    "Salary" numeric(18,2) NOT NULL,
    "DateHired" date NOT NULL,
    "EmploymentType" character varying(20) NOT NULL DEFAULT 'Full-time',
    "Status" character varying(50) NOT NULL DEFAULT 'Active',
    "ManagerID" integer,
    "IsManager" boolean NOT NULL,
    "FaceDataID" integer,
    "CreatedAt" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_Employees" PRIMARY KEY ("EmployeeID"),
    CONSTRAINT "FK_Employees_Departments_DepartmentID" FOREIGN KEY ("DepartmentID") REFERENCES "Departments" ("DepartmentID") ON DELETE RESTRICT,
    CONSTRAINT "FK_Employees_Employees_ManagerID" FOREIGN KEY ("ManagerID") REFERENCES "Employees" ("EmployeeID"),
    CONSTRAINT "FK_Employees_FaceData_FaceDataID" FOREIGN KEY ("FaceDataID") REFERENCES "FaceData" ("FaceDataID")
);

CREATE TABLE "Loans" (
    "LoanID" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeID" integer NOT NULL,
    "LoanType" text NOT NULL,
    "LoanAmount" numeric(18,2) NOT NULL,
    "LoanStatus" text NOT NULL,
    "DateIssued" timestamp with time zone NOT NULL,
    "DueDate" timestamp with time zone NOT NULL,
    "PaidLoan" numeric(18,2) NOT NULL,
    "LoanTerm" numeric NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Loans" PRIMARY KEY ("LoanID"),
    CONSTRAINT "FK_Loans_Employees_EmployeeID" FOREIGN KEY ("EmployeeID") REFERENCES "Employees" ("EmployeeID") ON DELETE CASCADE
);

CREATE TABLE "Logins" (
    "LoginID" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeID" integer NOT NULL,
    "Username" character varying(50) NOT NULL,
    "Password" character varying(255) NOT NULL,
    "LastLogin" timestamp without time zone,
    "FailedAttempts" integer NOT NULL DEFAULT 0,
    "IsLocked" boolean NOT NULL DEFAULT FALSE,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_Logins" PRIMARY KEY ("LoginID"),
    CONSTRAINT "FK_Logins_Employees_EmployeeID" FOREIGN KEY ("EmployeeID") REFERENCES "Employees" ("EmployeeID") ON DELETE CASCADE
);

CREATE INDEX "IX_Attendance_EmployeeID" ON "Attendance" ("EmployeeID");

CREATE INDEX "IX_Departments_ManagerID" ON "Departments" ("ManagerID");

CREATE UNIQUE INDEX "IX_Departments_Name" ON "Departments" ("DepartmentName");

CREATE INDEX "IX_Employees_DepartmentID" ON "Employees" ("DepartmentID");

CREATE UNIQUE INDEX "IX_Employees_Email" ON "Employees" ("Email");

CREATE INDEX "IX_Employees_FaceDataID" ON "Employees" ("FaceDataID");

CREATE INDEX "IX_Employees_ManagerID" ON "Employees" ("ManagerID");

CREATE INDEX "IX_Loans_EmployeeID" ON "Loans" ("EmployeeID");

CREATE INDEX "IX_Logins_EmployeeID" ON "Logins" ("EmployeeID");

CREATE UNIQUE INDEX "IX_Logins_Username" ON "Logins" ("Username");

ALTER TABLE "Attendance" ADD CONSTRAINT "FK_Attendance_Employees_EmployeeID" FOREIGN KEY ("EmployeeID") REFERENCES "Employees" ("EmployeeID") ON DELETE CASCADE;

ALTER TABLE "Departments" ADD CONSTRAINT "FK_Departments_Employees_ManagerID" FOREIGN KEY ("ManagerID") REFERENCES "Employees" ("EmployeeID");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260401025413_InitialPostgreSql', '9.0.4');

ALTER TABLE "Logins" ALTER COLUMN "LastLogin" TYPE timestamp with time zone;

ALTER TABLE "Employees" ALTER COLUMN "UpdatedAt" TYPE timestamp with time zone;

ALTER TABLE "Employees" ALTER COLUMN "CreatedAt" TYPE timestamp with time zone;

ALTER TABLE "Departments" ALTER COLUMN "DateCreated" TYPE timestamp with time zone;

ALTER TABLE "Attendance" ALTER COLUMN "UpdatedAt" TYPE timestamp with time zone;

ALTER TABLE "Attendance" ALTER COLUMN "CreatedAt" TYPE timestamp with time zone;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260401025730_UseTimestamptzForUtcDates', '9.0.4');

COMMIT;

