using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Microsoft.Extensions.Diagnostics.HealthChecks;
using Microsoft.ML.OnnxRuntime;
using System.Security.Cryptography;
using System.Text;
using HumanRepProj.Data;
using HumanRepProj.HealthChecks;
using HumanRepProj.Models;
using HumanRepProj.Services;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddRazorPages();
builder.Services.AddControllers();

// CORS
builder.Services.AddCors(options =>
{
    options.AddPolicy("DevelopmentCors", policy =>
    {
        policy.WithOrigins("http://localhost:7036")
              .AllowAnyHeader()
              .AllowAnyMethod()
              .AllowCredentials();
    });
});

// Session
builder.Services.AddSession(options =>
{
    options.IdleTimeout = TimeSpan.FromMinutes(30);
    options.Cookie.HttpOnly = true;
    options.Cookie.IsEssential = true;
});

// Authentication
builder.Services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
    .AddCookie(options =>
    {
        options.LoginPath = "/Login";
        options.LogoutPath = "/Logout";
        options.AccessDeniedPath = "/AccessDenied";
        options.ExpireTimeSpan = TimeSpan.FromMinutes(30);
        options.SlidingExpiration = true;
    });

// Database
builder.Services.AddDbContext<ApplicationDbContext>(options =>
{
    options.UseNpgsql(builder.Configuration.GetConnectionString("DefaultConnection"));
    options.ConfigureWarnings(warnings =>
        warnings.Ignore(RelationalEventId.PendingModelChangesWarning));
});

// Health checks
builder.Services.AddHealthChecks()
    .AddCheck<DbContextHealthCheck<ApplicationDbContext>>("database_check", HealthStatus.Unhealthy, new[] { "ready" });

// ONNX Runtime - YOLOv8n-face
var env = builder.Environment;
var wwwrootPath = env.WebRootPath;
var modelPath = Path.Combine(wwwrootPath, "models", "yolov8n-face.onnx");

if (!File.Exists(modelPath))
    throw new FileNotFoundException($"Model file not found at {modelPath}");

builder.Services.AddSingleton<InferenceSession>(provider =>
    new InferenceSession(modelPath, new Microsoft.ML.OnnxRuntime.SessionOptions
    {
        ExecutionMode = Microsoft.ML.OnnxRuntime.ExecutionMode.ORT_SEQUENTIAL
    }));

// Face Recognition Service
builder.Services.AddScoped<FaceRecognitionService>();
builder.Services.AddSingleton<IOnnxFaceDetectionService, OnnxFaceDetectionService>();

var app = builder.Build();

// Middleware pipeline
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    app.UseHsts();
    app.UseHttpsRedirection();
}
else
{
    app.UseDeveloperExceptionPage();
}

app.UseStaticFiles();     // ✅ Serves static files (e.g., ONNX models in `wwwroot/`)
app.UseRouting();         // ✅ Routes HTTP requests to endpoints
app.UseCors("DevelopmentCors");
app.UseSession();
app.UseAuthentication();
app.UseAuthorization();
app.UseHealthChecks("/health");

app.MapControllers();
app.MapRazorPages();
app.MapGet("/", () => Results.Redirect("/Login"));

// Ensure database exists and then verify connectivity during startup.
await EnsureDatabaseCreated(app.Services, app.Logger);
await ResetAccountsAndCreateAdmin(app.Services, app.Logger);
await EnsureEmployeeQrCodes(app.Services, app.Logger);
await VerifyDatabaseConnection(app.Services, app.Logger);

await app.RunAsync();

async Task EnsureDatabaseCreated(IServiceProvider services, ILogger logger)
{
    using var scope = services.CreateScope();
    var dbContext = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();
    try
    {
        logger.LogInformation("Applying database migrations...");
        await dbContext.Database.MigrateAsync();
        await EnsureWorkflowSchemaAsync(dbContext, logger);
        logger.LogInformation("Database migrations applied successfully");
    }
    catch (Exception ex)
    {
        logger.LogError(ex, "Failed to initialize database");
    }
}

async Task EnsureWorkflowSchemaAsync(ApplicationDbContext dbContext, ILogger logger)
{
    try
    {
        await dbContext.Database.ExecuteSqlRawAsync("""
CREATE TABLE IF NOT EXISTS "LeaveRequests" (
    "LeaveRequestID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EmployeeID" integer NOT NULL,
    "EmployeeName" character varying(120) NOT NULL,
    "LeaveType" character varying(80) NOT NULL,
    "StartDate" date NOT NULL,
    "EndDate" date NOT NULL,
    "Reason" character varying(500) NOT NULL,
    "ContactDuringLeave" character varying(40) NOT NULL,
    "Status" character varying(20) NOT NULL DEFAULT 'Pending',
    "SubmittedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ReviewedBy" character varying(50),
    "ReviewedAt" timestamp with time zone,
    "DecisionNote" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "IX_LeaveRequests_EmployeeID" ON "LeaveRequests" ("EmployeeID");
CREATE INDEX IF NOT EXISTS "IX_LeaveRequests_Status" ON "LeaveRequests" ("Status");

ALTER TABLE "Loans" ADD COLUMN IF NOT EXISTS "ReviewedBy" character varying(50);
ALTER TABLE "Loans" ADD COLUMN IF NOT EXISTS "ReviewedAt" timestamp with time zone;
ALTER TABLE "Loans" ADD COLUMN IF NOT EXISTS "DecisionNote" character varying(500);
""");

        logger.LogInformation("Workflow schema guard completed (LeaveRequests/Loans audit).");
    }
    catch (Exception ex)
    {
        logger.LogError(ex, "Workflow schema guard failed.");
        throw;
    }
}

async Task VerifyDatabaseConnection(IServiceProvider services, ILogger logger)
{
    using var scope = services.CreateScope();
    var dbContext = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();
    try
    {
        logger.LogInformation("Verifying database connection...");
        if (await dbContext.Database.CanConnectAsync())
        {
            logger.LogInformation("Database connection successful");
        }
        else
        {
            logger.LogError("Database connection failed");
        }
    }
    catch (Exception ex)
    {
        logger.LogError(ex, "Database verification failed");
    }
}

async Task ResetAccountsAndCreateAdmin(IServiceProvider services, ILogger logger)
{
    using var scope = services.CreateScope();
    var dbContext = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();

    try
    {
        logger.LogInformation("Ensuring admin account exists without resetting existing users...");

        var adminDepartment = await dbContext.Departments.FirstOrDefaultAsync(d => d.Name == "Administration");
        if (adminDepartment == null)
        {
            adminDepartment = new Department
            {
                Name = "Administration",
                Description = "System administration department",
                Performance = 100,
                Budget = 0,
                Status = "Active",
                DateCreated = DateTime.UtcNow
            };

            dbContext.Departments.Add(adminDepartment);
            await dbContext.SaveChangesAsync();
        }

        var adminEmployee = await dbContext.Employees.FirstOrDefaultAsync(e => e.Email == "admin@hris.local");
        if (adminEmployee == null)
        {
            adminEmployee = new Employee
            {
                FirstName = "System",
                LastName = "Admin",
                Email = "admin@hris.local",
                PhoneNumber = null,
                Address = "Local",
                DateOfBirth = new DateTime(1990, 1, 1),
                Gender = "Other",
                DepartmentID = adminDepartment.DepartmentID,
                Position = "Administrator",
                Salary = 0,
                DateHired = DateTime.UtcNow.Date,
                EmploymentType = "Full-time",
                Status = "Active",
                IsManager = true
            };

            dbContext.Employees.Add(adminEmployee);
            await dbContext.SaveChangesAsync();
            EmployeeQrCodeService.EnsureQrCodeForEmployee(adminEmployee.EmployeeID, app.Environment.WebRootPath);
        }

        var adminUser = await dbContext.ApplicationUsers
            .FirstOrDefaultAsync(u => u.Username.ToLower() == "admin");

        if (adminUser == null)
        {
            dbContext.ApplicationUsers.Add(new ApplicationUser
            {
                EmployeeID = adminEmployee.EmployeeID,
                Username = "admin",
                Password = HashPassword("admin"),
                LastLogin = null,
                FailedAttempts = 0,
                IsLocked = false
            });

            await dbContext.SaveChangesAsync();
            logger.LogInformation("Admin account created. Username: admin");
        }
        else
        {
            logger.LogInformation("Admin account already exists. Existing employee accounts preserved.");
        }
    }
    catch (Exception ex)
    {
        logger.LogError(ex, "Failed to reset accounts and create admin user");
    }
}

static string HashPassword(string plainTextPassword)
{
    var bytes = SHA256.HashData(Encoding.UTF8.GetBytes(plainTextPassword));
    return Convert.ToHexString(bytes);
}

async Task EnsureEmployeeQrCodes(IServiceProvider services, ILogger logger)
{
    using var scope = services.CreateScope();
    var dbContext = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();

    try
    {
        var employeeIds = await dbContext.Employees
            .AsNoTracking()
            .Select(e => e.EmployeeID)
            .ToListAsync();

        foreach (var employeeId in employeeIds)
        {
            EmployeeQrCodeService.EnsureQrCodeForEmployee(employeeId, app.Environment.WebRootPath);
        }

        logger.LogInformation("Ensured attendance QR files for {Count} employees.", employeeIds.Count);
    }
    catch (Exception ex)
    {
        logger.LogError(ex, "Failed while generating employee QR files at startup.");
    }
}